name: Deploy Main Project

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/deploy-pages.yml@main # Use @<branch-name> for best practice
    with:
      path: './dist'
