name: Deploy Main Project

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-workflow:
    uses: marcusexplores/.github/.github/workflows/deploy-pages.yml@main
    with:
      path: './dist'
    secrets: inherit
